// <auto-generated />
namespace TechTruffleShuffle.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class finalmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finalmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201711132136315_final migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
